"use strict";
var graphql_tag_1 = require('graphql-tag');
exports.gqlQueries = {
    me: (_a = ["\n    query Me {\n      me {\n        id,\n        firstName\n      }\n    }\n  "], _a.raw = ["\n    query Me {\n      me {\n        id,\n        firstName\n      }\n    }\n  "], graphql_tag_1.default(_a)),
    employees: (_b = ["\n    query Employees($storeId: Int) {\n      store(id: $storeId) {\n        employees {\n          id\n          user {\n            id\n            fullName\n            email\n            phone\n            isActive\n          }\n        }\n      }\n    }\n  "], _b.raw = ["\n    query Employees($storeId: Int) {\n      store(id: $storeId) {\n        employees {\n          id\n          user {\n            id\n            fullName\n            email\n            phone\n            isActive\n          }\n        }\n      }\n    }\n  "], graphql_tag_1.default(_b)),
    dealership: {
        store: (_c = ["\n      query DealershipStore($storeId: Int) {\n        store(id: $storeId) {\n          id\n          name\n          primaryContact {\n            user {\n              fullName\n              email\n              phone\n            }\n          }\n          organization {\n            id\n            name\n            groups {\n              id\n              name\n            }\n            regions(is_active: true) {\n              id\n              name\n            }\n          }\n          groups {\n            id\n            name\n          }\n          region {\n            id\n            name\n          }\n        }\n      }\n    "], _c.raw = ["\n      query DealershipStore($storeId: Int) {\n        store(id: $storeId) {\n          id\n          name\n          primaryContact {\n            user {\n              fullName\n              email\n              phone\n            }\n          }\n          organization {\n            id\n            name\n            groups {\n              id\n              name\n            }\n            regions(is_active: true) {\n              id\n              name\n            }\n          }\n          groups {\n            id\n            name\n          }\n          region {\n            id\n            name\n          }\n        }\n      }\n    "], graphql_tag_1.default(_c))
    }
};
var _a, _b, _c;
//# sourceMappingURL=gqlQueries.js.map